# Build container image for this app using Azure Pipelines
# http://docs.microsoft.com/azure/devops/pipelines/languages/docker?view=vsts

trigger: none 

pr: none

pool:
  vmImage: 'Ubuntu 16.04'

steps:
- task: AzureCLI@1
  displayName: 'Azure CLI'
  inputs:
    azureSubscription: 'CDW - Microsoft AIRS 01 (b9c770d1-cde9-4da3-ae40-95ce1a4fac0c)'
    scriptLocation: inlineScript
    inlineScript: 'az acr build --registry $(acr_name) --image $(image_name):$(image_tag) .'