pool:
  vmImage: 'Ubuntu 16.04'

trigger: none 

pr: none

resources:
  containers:
  - container: MyContainer 
    type: ACR
    connection: 'CDW - Microsoft AIRS 01 (b9c770d1-cde9-4da3-ae40-95ce1a4fac0c)'
    registry: cdwms
    image: $(image_name):$(image_tag)

steps:
- bash: echo "Hello, World!"
  displayName: Bash Script
  name: Test Script