CREATE DATABASE MyData
GO

USE MyData
GO

CREATE TABLE [dbo].[Items](
  [Id] [int] IDENTITY(1,1) NOT NULL,
  [Value] [nvarchar](50) NOT NULL,
  CONSTRAINT [PK_Items] PRIMARY KEY CLUSTERED (
    [Id] ASC
  ) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

INSERT INTO Items VALUES('Test Value #1')
INSERT INTO Items VALUES('Test Value #2')
GO